### ISSUE TITLE
Google site tracking page.

### ISSUE THREAD

**Issue by virtadpt** [urfdvw/CircuitPython-online-IDE#2]
Are you sure the file google2ba7634dfbf3b91d.html is supposed to be in there?

**Comment by urfdvw** [comment]
It was used for site ownership verification. It needs to remain as long as I verify it. If you want to fork or download the project for your usages no need to have that file.

**Comment by virtadpt** [comment]
I was just checking.  It seems kind of sensitive, but if it's not an oversight then no worries.
